# Generated by Django 4.2.7 on 2024-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polls_color_polls_name_polls_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='x', max_length=200)),
                ('title', models.CharField(default='x', max_length=200)),
                ('post', models.CharField(default='x', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='polls',
            old_name='color',
            new_name='play',
        ),
        migrations.RenameField(
            model_name='polls',
            old_name='url',
            new_name='play2',
        ),
        migrations.AddField(
            model_name='polls',
            name='title',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
