# Generated by Django 4.2.7 on 2024-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_post_rename_color_polls_play_rename_url_polls_play2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='mood',
        ),
    ]
